### ISSUE TITLE
Error on iMac 11, 3(Real Mac)

### ISSUE THREAD

**Issue by Helloyunho** [vit9696/macserial#2]
An error occurred on Serial Number Model

```
Model:  DB6 - Unknown, please report!
```

**Comment by roddy20** [comment]
are you sure? macserial  -i QP043014DB6
       Country:   QP - USA
          Year:    0 - 2010
          Week:   43 - 43 (22.10.2010-28.10.2010)
          Line:  014 - 38 (copy 1)
         Model:  DB6 - iMac11,3
         Valid: Possibly

**Comment by vit9696** [comment]
I suppose @Helloyunho was using the earlier version (2.0.1) which did not have #1 merged in. I published a new binary release (2.0.2), it should solve the issue.
